[tool.poetry]
name = "anomaly-detection"
version = "0.1.0"
description = "Simple anomaly detection algorithms and benchmarking utilities."
authors = ["Diogo Ribeiro <diogo.debastos.ribeiro@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
matplotlib = "*"
pandas = "*"
scikit-learn = "*"
scikit-sos = "*"
pyod = "*"
torch = "*"
tensorflow = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pre-commit = "*"

[tool.poetry.scripts]
benchmark-cli = "cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
